// Pre-curated NC Residential Code citations by trade.
// These are real code sections (curated manually), NOT generated by an LLM.
// When the LLM references a citation not in this list, it gets flagged as
// `citation_verified: false` by the repair guide engine.

export interface NCCodeCitation {
  section: string;
  title: string;
  trade: string;
  summary: string;
}

const CITATIONS: NCCodeCitation[] = [
  // ── Electrical ──────────────────────────────────────────────────────────
  {
    section: "NEC 2020 Art. 210",
    title: "Branch circuits",
    trade: "Electrical",
    summary: "General requirements for branch circuits, including receptacle spacing (rooms) and circuit rating.",
  },
  {
    section: "NEC 210.12",
    title: "Arc-fault circuit-interrupter protection",
    trade: "Electrical",
    summary: "AFCI protection required for 120V, 15- and 20-amp branch circuits supplying outlets in dwelling unit living areas.",
  },
  {
    section: "NEC 314.16",
    title: "Box fill",
    trade: "Electrical",
    summary: "Maximum number of conductors permitted in outlet, junction, and pull boxes.",
  },
  {
    section: "NCRC E3902",
    title: "Bathroom receptacles",
    trade: "Electrical",
    summary: "Receptacle outlets required in bathrooms; shall be GFCI protected.",
  },
  {
    section: "NEC 210.8",
    title: "GFCI protection",
    trade: "Electrical",
    summary: "GFCI required for receptacles in bathrooms, garages, kitchens, outdoors, basements, and crawl spaces.",
  },
  // ── Plumbing ────────────────────────────────────────────────────────────
  {
    section: "NCRC P2503.5",
    title: "DWV system testing",
    trade: "Plumbing",
    summary: "Drain, waste, and vent system shall be tested with water or air prior to covering.",
  },
  {
    section: "NCRC P2801.3",
    title: "Water heater requirements",
    trade: "Plumbing",
    summary: "Water heaters shall be sized, installed, and provided with required safety devices and clearance.",
  },
  {
    section: "NCPC 604.1",
    title: "Potable water supply",
    trade: "Plumbing",
    summary: "Potable water systems shall be provided for all plumbing fixtures intended for human contact.",
  },
  // ── HVAC ────────────────────────────────────────────────────────────────
  {
    section: "NCRC M1401.3",
    title: "HVAC equipment",
    trade: "HVAC",
    summary: "Heating and cooling equipment installation requirements, including access, clearances, and supports.",
  },
  {
    section: "NCRC N1103.3",
    title: "Programmable thermostat",
    trade: "HVAC",
    summary: "Dwelling units shall have at least one programmable thermostat to control the heating or cooling system.",
  },
  {
    section: "NCRC Section 806",
    title: "Ventilation",
    trade: "HVAC",
    summary: "Whole-house mechanical ventilation requirements for dwelling units.",
  },
  // ── Structural ──────────────────────────────────────────────────────────
  {
    section: "NCRC R502",
    title: "Wood floor framing",
    trade: "Structural",
    summary: "Floor joists, girders, subflooring, and spans for wood frame floors.",
  },
  {
    section: "NCRC R403",
    title: "Foundations",
    trade: "Structural",
    summary: "Footings, concrete, masonry, and foundation wall requirements.",
  },
  {
    section: "NCRC R301.5",
    title: "Live loads",
    trade: "Structural",
    summary: "Minimum uniformly distributed live loads for floors and other components (e.g., 40 psf residential).",
  },
  {
    section: "NCRC R507",
    title: "Decks",
    trade: "Structural",
    summary: "Deck construction requirements including ledger attachment, posts, beams, and guards.",
  },
  // ── Roofing ─────────────────────────────────────────────────────────────
  {
    section: "NCRC R905",
    title: "Roof covering",
    trade: "Roofing",
    summary: "Materials, underlayment, and installation requirements for roof coverings (asphalt shingles, etc.).",
  },
  {
    section: "NCRC R801",
    title: "Roof ventilation",
    trade: "Roofing",
    summary: "Ventilation requirements for enclosed attics and rafter spaces.",
  },
  {
    section: "NCRC R903",
    title: "Roof flashing",
    trade: "Roofing",
    summary: "Flashing requirements at roof valleys, penetrations, and intersections with vertical surfaces.",
  },
  // ── General ─────────────────────────────────────────────────────────────
  {
    section: "NCRC R102.7",
    title: "Existing buildings",
    trade: "General",
    summary: "Provisions for additions, alterations, and repairs to existing buildings.",
  },
  {
    section: "NCRC R109.1",
    title: "Required inspections",
    trade: "General",
    summary: "Building inspections required — footing, framing, plumbing, mechanical, electrical, and final.",
  },
  {
    section: "NCRC R105",
    title: "Permits",
    trade: "General",
    summary: "Work requiring a permit, application process, and inspections under the building official.",
  },
];

const TRADE_ALIASES: Record<string, string[]> = {
  electrical: ["electric", "wiring", "panel"],
  plumbing: ["plumber", "pipe", "water"],
  hvac: ["heating", "cooling", "ventilation", "air conditioning", "mechanical"],
  structural: ["foundation", "framing", "floor", "framing", "deck"],
  roofing: ["roof", "shingle"],
  general: ["inspection", "permit", "existing building"],
};

export function getCitationForTrade(trade: string): NCCodeCitation[] {
  const normalized = trade.trim().toLowerCase();
  if (!normalized) return [];

  // Exact trade match first.
  const exact = CITATIONS.filter(
    (c) => c.trade.toLowerCase() === normalized
  );
  if (exact.length > 0) return exact;

  // Alias match.
  for (const [canonical, aliases] of Object.entries(TRADE_ALIASES)) {
    if (aliases.some((a) => normalized.includes(a))) {
      return CITATIONS.filter((c) => c.trade.toLowerCase() === canonical);
    }
  }

  return [];
}

export function listAllCitations(): NCCodeCitation[] {
  return [...CITATIONS];
}
